/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.login;

import MyClass.Authors;;
import MyClass.Func_Class;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rocky
 */
public class AuthorListForm extends javax.swing.JFrame {

    MyClass.Authors authors= new MyClass.Authors();
    public   String formType="";
    public AuthorListForm() {
        initComponents();
       // populatedJtabledWithGenres();
        this.setLocationRelativeTo(null);
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(1,50,67));
       jPanel1.setBorder(panelHeaderBorder);
       MyClass.Func_Class func = new Func_Class();
                    func.displayImage(
    75,
    50,null,
    "/com/image/notep.png",
    jLabel_formTitle
);
   jTable_authors.setSelectionBackground(new Color(249,105,14));
   jTable_authors.setSelectionForeground(Color.white);
   jTable_authors.setRowHeight(30);
   jTable_authors.setShowGrid(false);
   jTable_authors.setBackground(new Color(248,248,248));
   jTable_authors.setShowHorizontalLines(true);
   jTable_authors.setGridColor(Color.orange);
   jTable_authors.getTableHeader().setBackground(new Color(34,167,240));
   jTable_authors.getTableHeader().setForeground(Color.white);
   jTable_authors.getTableHeader().setFont(new Font("Times New Roman",Font.BOLD,18));
   jTable_authors.getTableHeader().setOpaque(false);
   
   populatedJtabledWithAuthor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_formTitle = new javax.swing.JLabel();
        jLabel_closeform = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_authors = new javax.swing.JTable();
        jButton_select_author = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_formTitle.setBackground(new java.awt.Color(1, 50, 67));
        jLabel_formTitle.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel_formTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_formTitle.setText("    Authors list");
        jLabel_formTitle.setOpaque(true);

        jLabel_closeform.setBackground(new java.awt.Color(1, 50, 67));
        jLabel_closeform.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_closeform.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_closeform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_closeform.setText("X");
        jLabel_closeform.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_closeform.setOpaque(true);
        jLabel_closeform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeformMouseClicked(evt);
            }
        });

        jTable_authors.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jTable_authors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_authors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_authorsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_authors);

        jButton_select_author.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton_select_author.setText("SELECT AUTHOR ");
        jButton_select_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_select_authorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_closeform, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jButton_select_author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel_closeform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_select_author, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_authorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_authorsMouseClicked
       

       
    }//GEN-LAST:event_jTable_authorsMouseClicked

    private void jLabel_closeformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeformMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_closeformMouseClicked

    private void jButton_select_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_select_authorActionPerformed
        int index =jTable_authors.getSelectedRow();
        int id=Integer.parseInt(jTable_authors.getValueAt(index,0).toString());
        String firstName=jTable_authors.getValueAt(index,1).toString();
        String lastName=jTable_authors.getValueAt(index,2).toString();
        String fullName= firstName+" "+lastName;
        if(formType.equals("edit"))
           EditBookForm.displayAuthorData(id, fullName);  
        
        else
        AddBookForm.displayAuthorData(id, fullName);
        this.dispose();
    }//GEN-LAST:event_jButton_select_authorActionPerformed

public void populatedJtabledWithAuthor() {
    Authors author = new Authors();
    ArrayList<Authors> authorlist = author.AuthorList();
    
    // Check if genreslist is not null and not empty
    if (authorlist != null && !authorlist.isEmpty()) {
        String[] colNames = { "ID", "FIRSTNAME", "LASTNAME", "EXPERTISE", "ABOUT" };
        Object[][] rows = new Object[authorlist.size()][colNames.length];
        
        for (int i = 0; i < authorlist.size(); i++) {
            rows[i][0] = authorlist.get(i).getId();
            rows[i][1] = authorlist.get(i).getFirstName();
            rows[i][2] = authorlist.get(i).getLastName();
            rows[i][3] = authorlist.get(i).getField_of_expertise();
            rows[i][4] = authorlist.get(i).getAbout(); 
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_authors.setModel(model);
    } 
}



   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                   // javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthorListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthorListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthorListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthorListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthorListForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_select_author;
    private javax.swing.JLabel jLabel_closeform;
    private javax.swing.JLabel jLabel_formTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_authors;
    // End of variables declaration//GEN-END:variables
}
