/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.login;

import MyClass.Authors;;
import MyClass.Func_Class;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rocky
 */
public class ManageUserForm extends javax.swing.JFrame {

    MyClass.Users user= new MyClass.Users();
    public ManageUserForm() {
        initComponents();
       // populatedJtabledWithGenres();
        this.setLocationRelativeTo(null);
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(242,217,132));
       jPanel1.setBorder(panelHeaderBorder);
       MyClass.Func_Class func = new Func_Class();
                    func.displayImage(
    90,
    80,null,
    "/com/image/house.png",
    jLabel_formTitle
);
   jTable_users.setSelectionBackground(new Color(249,105,14));
   jTable_users.setSelectionForeground(Color.white);
   jTable_users.setRowHeight(30);
   jTable_users.setShowGrid(false);
   jTable_users.setBackground(new Color(248,248,248));
   jTable_users.setShowHorizontalLines(true);
   jTable_users.setGridColor(Color.orange);
   jTable_users.getTableHeader().setBackground(new Color(34,167,240));
   jTable_users.getTableHeader().setForeground(Color.white);
   jTable_users.getTableHeader().setFont(new Font("Times New Roman",Font.BOLD,18));
   jTable_users.getTableHeader().setOpaque(false);
   jLabel_emptyfirst.setForeground(Color.white);
   jLabel_emptylast.setForeground(Color.white);
   jLabel_emptyuser1.setForeground(Color.white);
   jLabel_emptypassword.setForeground(Color.white);
   populatedJtabledWithUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_formTitle = new javax.swing.JLabel();
        jLabel_closeform = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_firstname_ = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_users = new javax.swing.JTable();
        jLabel_emptyfirst = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_emptylast = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField_1 = new javax.swing.JPasswordField();
        jPasswordField_2 = new javax.swing.JPasswordField();
        jLabel_emptypassword = new javax.swing.JLabel();
        jLabel_emptyuser1 = new javax.swing.JLabel();
        jCheckBox_setAdmin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_formTitle.setBackground(new java.awt.Color(242, 217, 132));
        jLabel_formTitle.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel_formTitle.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_formTitle.setText("    Manage Users");
        jLabel_formTitle.setOpaque(true);

        jLabel_closeform.setBackground(new java.awt.Color(242, 217, 132));
        jLabel_closeform.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_closeform.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_closeform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_closeform.setText("X");
        jLabel_closeform.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_closeform.setOpaque(true);
        jLabel_closeform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeformMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("First NAME:");

        jTextField_id.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jTextField_id.setEnabled(false);

        jTextField_firstname_.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jTextField_firstname_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstname_ActionPerformed(evt);
            }
        });

        jButton_add.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton_add.setText("ADD");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_edit.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton_edit.setText("EDIT");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_delete.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton_delete.setText("DELETE");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jTable_users.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jTable_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_usersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_users);

        jLabel_emptyfirst.setForeground(new java.awt.Color(243, 0, 0));
        jLabel_emptyfirst.setText("\"enter the first name");
        jLabel_emptyfirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptyfirstMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("LAST NAME:");

        jLabel_emptylast.setForeground(new java.awt.Color(243, 0, 0));
        jLabel_emptylast.setText("\"enter the second name");
        jLabel_emptylast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptylastMouseClicked(evt);
            }
        });

        jTextField_username.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Username:");

        jTextField_lastname.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Retype password:");

        jPasswordField_1.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N

        jPasswordField_2.setFont(new java.awt.Font("Sylfaen", 1, 13)); // NOI18N

        jLabel_emptypassword.setForeground(new java.awt.Color(243, 0, 0));
        jLabel_emptypassword.setText("\"enter the password");
        jLabel_emptypassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptypasswordMouseClicked(evt);
            }
        });

        jLabel_emptyuser1.setForeground(new java.awt.Color(243, 0, 0));
        jLabel_emptyuser1.setText("\"enter the username");
        jLabel_emptyuser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptyuser1MouseClicked(evt);
            }
        });

        jCheckBox_setAdmin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox_setAdmin.setText("Make this user an admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_delete))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPasswordField_2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPasswordField_1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addComponent(jTextField_lastname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_firstname_, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_emptyfirst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_emptylast, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_emptypassword, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_emptyuser1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_setAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_closeform, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel_closeform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_firstname_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_emptyfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_emptylast, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_emptyuser1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField_1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_emptypassword)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_setAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_edit)
                            .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeformMouseClicked
       this.dispose();
    }//GEN-LAST:event_jLabel_closeformMouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        String fname=jTextField_firstname_.getText();
        String lname=jTextField_lastname.getText();
        String username=jTextField_username.getText();
        String password1=String.valueOf(jPasswordField_1.getPassword());
        String password2=String.valueOf(jPasswordField_2.getPassword());
        String userType="user";
        if(jCheckBox_setAdmin.isSelected()){  userType="admin";    }
    
        if (fname.trim().isEmpty()){
           jLabel_emptyfirst.setForeground(Color.red);
          
        }else if (lname.trim().isEmpty()){
          jLabel_emptylast.setForeground(Color.red);
        }
        else if (username.trim().isEmpty()){
         // jLabel_emptypassword.setVisible(true);
         jLabel_emptyuser1.setForeground(Color.red);
        }
        else if (password1.trim().isEmpty()){
          //jLabel_emptypassword.setVisible(true);
          jLabel_emptypassword.setForeground(Color.red);
        }
        else if (!password1.equals(password2)){
          //jLabel_emptypassword.setVisible(true);
          JOptionPane.showMessageDialog(null, "Retype the correct password " ,"password error", 0);
        }
        else if(user.checkUsernameExists(0,username)){
            JOptionPane.showMessageDialog(null, "This username is already exists Try another one " ,"Username error", 0); 
        }
        else{
           
          user.addUsers(fname,lname,username,password1,userType);
          populatedJtabledWithUser();
           jTextField_id.setText("");
                   jTextField_firstname_.setText("");
                   jTextField_lastname.setText("");
                   jTextField_username.setText("");
                  jPasswordField_1.setText("");
                  jPasswordField_2.setText("");
                   jCheckBox_setAdmin.setSelected(false);
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        
        String fname=jTextField_firstname_.getText();
        String lname=jTextField_lastname.getText();
        String username=jTextField_username.getText();
       String password1=String.valueOf(jPasswordField_1.getPassword());
       String password2=String.valueOf(jPasswordField_2.getPassword());
       String userType ="user";
       if (jCheckBox_setAdmin.isSelected()){
           userType ="admin";
       }
        
         if (fname.trim().isEmpty()){
           jLabel_emptyfirst.setForeground(Color.red);;
          
        }else if (lname.trim().isEmpty()){
          jLabel_emptylast.setForeground(Color.red);
        } else if (username.trim().isEmpty()){
         // jLabel_emptypassword.setVisible(true);
         jLabel_emptyuser1.setForeground(Color.red);
        }
        else if (password1.trim().isEmpty()){
          //jLabel_emptypassword.setVisible(true);
          jLabel_emptypassword.setForeground(Color.red);
        }
        else if (!password1.equals(password2)){
          //jLabel_emptypassword.setVisible(true);
          JOptionPane.showMessageDialog(null, "Retype the correct password " ,"password error", 0);
        }
        
        else{
            try{
                int id=Integer.parseInt(jTextField_id.getText());
               if(user.checkUsernameExists(id,username)){
            JOptionPane.showMessageDialog(null, "This username is already exists Try another one " ,"Username error", 0); 
                }
               else{
             user.editUsers(id,fname,lname,username,password1,userType); 
             populatedJtabledWithUser();
              jTextField_id.setText("");
                   jTextField_firstname_.setText("");
                   jTextField_lastname.setText("");
                   jTextField_username.setText("");
                  jPasswordField_1.setText("");
                  jPasswordField_2.setText("");
                   jCheckBox_setAdmin.setSelected(false);
               }
            }
           catch(NumberFormatException ex){
             JOptionPane.showMessageDialog(null, "Select user you want to edit from table " ,"No id selected", 0);  
           }
          
        }
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
         try{
                   int id =Integer.valueOf(jTextField_id.getText());
                     int confirm = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this Users ?","confirmation Box",JOptionPane.YES_NO_OPTION);
               if(confirm==JOptionPane.YES_OPTION){
                     user.removeUsers(id);
                    }
                    
                    populatedJtabledWithUser();
                   jTextField_id.setText("");
                   jTextField_firstname_.setText("");
                   jTextField_lastname.setText("");
                   jTextField_username.setText("");
                  jPasswordField_1.setText("");
                  jPasswordField_2.setText("");
                   jCheckBox_setAdmin.setSelected(false);
              }
           catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "invalid User id"+ex.getMessage(), "error", 0);
           }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jTable_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_usersMouseClicked
        int index =jTable_users.getSelectedRow();
String id=jTable_users.getValueAt(index,0).toString();
String firstName=jTable_users.getValueAt(index,1).toString();
String lastName=jTable_users.getValueAt(index,2).toString();
String username=jTable_users.getValueAt(index,3).toString();
String password=jTable_users.getValueAt(index,4).toString();
String userType=jTable_users.getValueAt(index,5).toString();

jTextField_id.setText(id);
jTextField_firstname_.setText(firstName);
jTextField_lastname.setText(lastName);
jTextField_username.setText(username);
jPasswordField_1.setText(password);
jPasswordField_2.setText(password);
if (userType.equals("admin")){
    jCheckBox_setAdmin.setSelected(true);
}else{
    jCheckBox_setAdmin.setSelected(false);
}

    }//GEN-LAST:event_jTable_usersMouseClicked

public void populatedJtabledWithUser() {
ArrayList<MyClass.Users> userlist = user.UsersList();
String[] colNames = { "ID", "F-NAME", "L-NAME", "Username", "Password", "Type" };
Object[][] rows = new Object[userlist.size()][colNames.length];

for (int a = 0; a < userlist.size(); a++) {
    rows[a][0] = userlist.get(a).getId();
    rows[a][1] = userlist.get(a).getFirstname();
    rows[a][2] = userlist.get(a).getLastname();
    rows[a][3] = userlist.get(a).getUsername();
    rows[a][4] = userlist.get(a).getPassword();
    rows[a][5] = userlist.get(a).getUserType();
}
DefaultTableModel model = new DefaultTableModel(rows, colNames);
jTable_users.setModel(model);
        
}



   
    private void jLabel_emptyfirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptyfirstMouseClicked
        jLabel_emptyfirst.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_emptyfirstMouseClicked

    private void jTextField_firstname_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstname_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstname_ActionPerformed

    private void jLabel_emptylastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptylastMouseClicked
        jLabel_emptylast.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_emptylastMouseClicked

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jLabel_emptypasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptypasswordMouseClicked
        jLabel_emptypassword.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_emptypasswordMouseClicked

    private void jLabel_emptyuser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptyuser1MouseClicked
        jLabel_emptyuser1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_emptyuser1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                   // javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JCheckBox jCheckBox_setAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_closeform;
    private javax.swing.JLabel jLabel_emptyfirst;
    private javax.swing.JLabel jLabel_emptylast;
    private javax.swing.JLabel jLabel_emptypassword;
    private javax.swing.JLabel jLabel_emptyuser1;
    private javax.swing.JLabel jLabel_formTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_1;
    private javax.swing.JPasswordField jPasswordField_2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_users;
    private javax.swing.JTextField jTextField_firstname_;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_lastname;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
