/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.login;

import MyClass.Authors;;
import MyClass.Func_Class;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rocky
 */
public class ManageAuthorsForm1 extends javax.swing.JFrame {

    MyClass.Authors authors= new MyClass.Authors();
    public ManageAuthorsForm1() {
        initComponents();
       // populatedJtabledWithGenres();
        this.setLocationRelativeTo(null);
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(1,50,67));
       jPanel1.setBorder(panelHeaderBorder);
       MyClass.Func_Class func = new Func_Class();
                    func.displayImage(
    75,
    50,null,
    "/com/image/notep.png",
    jLabel_formTitle
);
   jTable_authors.setSelectionBackground(new Color(249,105,14));
   jTable_authors.setSelectionForeground(Color.white);
   jTable_authors.setRowHeight(30);
   jTable_authors.setShowGrid(false);
   jTable_authors.setBackground(new Color(248,248,248));
   jTable_authors.setShowHorizontalLines(true);
   jTable_authors.setGridColor(Color.orange);
   jTable_authors.getTableHeader().setBackground(new Color(34,167,240));
   jTable_authors.getTableHeader().setForeground(Color.white);
   jTable_authors.getTableHeader().setFont(new Font("Times New Roman",Font.BOLD,18));
   jTable_authors.getTableHeader().setOpaque(false);
   jLabel_emptyfirst.setVisible(false);
   jLabel_emptylast.setVisible(false);
   populatedJtabledWithAuthor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_formTitle = new javax.swing.JLabel();
        jLabel_closeform = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_firstname_ = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_authors = new javax.swing.JTable();
        jLabel_emptyfirst = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_emptylast = new javax.swing.JLabel();
        jTextField_expertise = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_lastname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_about = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_formTitle.setBackground(new java.awt.Color(1, 50, 67));
        jLabel_formTitle.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel_formTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_formTitle.setText("    Manage Authors");
        jLabel_formTitle.setOpaque(true);

        jLabel_closeform.setBackground(new java.awt.Color(1, 50, 67));
        jLabel_closeform.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_closeform.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_closeform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_closeform.setText("X");
        jLabel_closeform.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_closeform.setOpaque(true);
        jLabel_closeform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeformMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("First NAME:");

        jTextField_id.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N

        jTextField_firstname_.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jTextField_firstname_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstname_ActionPerformed(evt);
            }
        });

        jButton_add.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton_add.setText("ADD");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_edit.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton_edit.setText("EDIT");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_delete.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton_delete.setText("DELETE");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jTable_authors.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jTable_authors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_authors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_authorsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_authors);

        jLabel_emptyfirst.setForeground(new java.awt.Color(243, 0, 0));
        jLabel_emptyfirst.setText("\"enter the first name");
        jLabel_emptyfirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptyfirstMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("LAST NAME:");

        jLabel_emptylast.setForeground(new java.awt.Color(243, 0, 0));
        jLabel_emptylast.setText("\"enter the second name");
        jLabel_emptylast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptylastMouseClicked(evt);
            }
        });

        jTextField_expertise.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jTextField_expertise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_expertiseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText(" ABOUT:");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(" EXPERTISE:");

        jTextField_lastname.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N

        jTextArea_about.setColumns(20);
        jTextArea_about.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea_about.setRows(5);
        jScrollPane2.setViewportView(jTextArea_about);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addComponent(jTextField_expertise)
                        .addComponent(jTextField_lastname)
                        .addComponent(jTextField_firstname_)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_emptyfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_emptylast, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_id))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_delete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_closeform, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel_closeform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_firstname_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_emptyfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_emptylast, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_expertise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_edit)
                            .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeformMouseClicked
       this.dispose();
    }//GEN-LAST:event_jLabel_closeformMouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        String fname=jTextField_firstname_.getText();
        String lname=jTextField_lastname.getText();
        String expertise=jTextField_expertise.getText();
        String about=jTextArea_about.getText();
        
        if (fname.trim().isEmpty()){
           jLabel_emptyfirst.setVisible(true);
          
        }else if (lname.trim().isEmpty()){
          jLabel_emptylast.setVisible(true);
        }
        
        else{
           
           authors.addAuthors(fname,lname,expertise,about);
           populatedJtabledWithAuthor();
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        String fname=jTextField_firstname_.getText();
        String lname=jTextField_lastname.getText();
        String expertise=jTextField_expertise.getText();
        String about=jTextArea_about.getText();
        
         if (fname.trim().isEmpty()){
           jLabel_emptyfirst.setVisible(true);
          
        }else if (lname.trim().isEmpty()){
          jLabel_emptylast.setVisible(true);
        }else{
              try{
                   int id =Integer.valueOf(jTextField_id.getText());
                   authors.editAuthors(id,fname,lname,expertise,about);
                   populatedJtabledWithAuthor();
              }
           catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "invalid Genre id"+ex.getMessage(), "error", 0);
           }
       
        }
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
         try{
                   int id =Integer.valueOf(jTextField_id.getText());
                   int confirm = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this Authors ?","confirmation Box",JOptionPane.YES_NO_OPTION);
               if(confirm==JOptionPane.YES_OPTION){
                     authors.removeAuthors(id);
                    }
                   
                   populatedJtabledWithAuthor();
                   jTextField_id.setText("");
                   jTextField_firstname_.setText("");
                   jTextField_lastname.setText("");
                   jTextField_expertise.setText("");
                   jTextArea_about.setText("");
                   
              }
           catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "invalid Authors id"+ex.getMessage(), "error", 0);
           }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jTable_authorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_authorsMouseClicked
        int index =jTable_authors.getSelectedRow();
String id=jTable_authors.getValueAt(index,0).toString();
String firstName=jTable_authors.getValueAt(index,1).toString();
String lastName=jTable_authors.getValueAt(index,2).toString();
String expertise=jTable_authors.getValueAt(index,3).toString();
String about=jTable_authors.getValueAt(index,4).toString();

jTextField_id.setText(id);
jTextField_firstname_.setText(firstName);
jTextField_lastname.setText(lastName);
jTextField_expertise.setText(expertise);
jTextArea_about.setText(about);
    }//GEN-LAST:event_jTable_authorsMouseClicked

public void populatedJtabledWithAuthor() {
    Authors author = new Authors();
    ArrayList<Authors> authorlist = author.AuthorList();
    
    // Check if genreslist is not null and not empty
    if (authorlist != null && !authorlist.isEmpty()) {
        String[] colNames = { "ID", "FIRSTNAME", "LASTNAME", "EXPERTISE", "ABOUT" };
        Object[][] rows = new Object[authorlist.size()][colNames.length];
        
        for (int i = 0; i < authorlist.size(); i++) {
            rows[i][0] = authorlist.get(i).getId();
            rows[i][1] = authorlist.get(i).getFirstName();
            rows[i][2] = authorlist.get(i).getLastName();
            rows[i][3] = authorlist.get(i).getField_of_expertise();
            rows[i][4] = authorlist.get(i).getAbout(); 
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable_authors.setModel(model);
    } 
}



   
    private void jLabel_emptyfirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptyfirstMouseClicked
        jLabel_emptyfirst.setVisible(false);
    }//GEN-LAST:event_jLabel_emptyfirstMouseClicked

    private void jTextField_firstname_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstname_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstname_ActionPerformed

    private void jLabel_emptylastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptylastMouseClicked
        jLabel_emptylast.setVisible(false);
    }//GEN-LAST:event_jLabel_emptylastMouseClicked

    private void jTextField_expertiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_expertiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_expertiseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                   // javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAuthorsForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAuthorsForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAuthorsForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAuthorsForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAuthorsForm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_closeform;
    private javax.swing.JLabel jLabel_emptyfirst;
    private javax.swing.JLabel jLabel_emptylast;
    private javax.swing.JLabel jLabel_formTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_authors;
    private javax.swing.JTextArea jTextArea_about;
    private javax.swing.JTextField jTextField_expertise;
    private javax.swing.JTextField jTextField_firstname_;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_lastname;
    // End of variables declaration//GEN-END:variables
}
